### ISSUE TITLE
Convert the Assassin to a setting

### ISSUE THREAD

**Issue by Anusien** [Anusien/Town-Of-Us#132]
The Assassin is a great role in the way it prevents people from role calling. It also introduces an extra dimension to the impostor play where you can deduce roles and win that way. The Assassin is so mandatory that it chokes out other impostor roles.

What we want to do is get rid of the Assassin role and just give every impostor the ability to guess. The same rules apply: guess correctly and the target dies. Guess wrong and the impostor dies. We will have a setting for the total number of guesses that impostors are allow. This pool is shared between all the impostors.

Sharing a pool gives an incentive to not guess randomly when you think you're getting voted out. It also prevents crew from role calling once a single impostor is gone because the total number of guesses are unaffected.

**Comment by k-electron** [comment]
can the pool be configurable so that in a low player count game the og assassin can exist.

**Comment by Anusien** [comment]
This is intended to replace the Assassin entirely.

The one counterplay you lose is "If I get assassinated, it's X" but I'm not convinced that's something we'll miss.

**Comment by k-electron** [comment]
> This is intended to replace the Assassin entirely.

Right, i mean if the pool is configurable then I can have multiple kills from the same imposter in one night if they have solved the game.

**Comment by Anusien** [comment]
> > This is intended to replace the Assassin entirely.
> 
> Right, i mean if the pool is configurable then I can have multiple kills from the same imposter in one night if they have solved the game.

Correct. If there are 5 possible kills, one player could use all 5 in one meeting (if the setting is turned on).

**Comment by Anusien** [comment]
https://github.com/Anusien/Town-Of-Us/pull/137
