### ISSUE TITLE
[New role] Wannabe - the crew that wants to be an imposter

### ISSUE THREAD

**Issue by k-electron** [Anusien/Town-Of-Us#154]
A crew role that looks like an imposter to the imposters. The wannabe can enter vents but not travel using vents.

Settings:
Sheriff kills Wannabe: On / Off (default)
Wannabe has imposter vision: On (default) / Off

**Comment by Anusien** [comment]
https://github.com/Anusien/Town-Of-Us/issues/129

**Comment by Anusien** [comment]
Dupe of #129
