### ISSUE TITLE
Show last game's roles in the lobby

### ISSUE THREAD

**Issue by Anusien** [Anusien/Town-Of-Us#66]
One of the downsides to the mod is that you can't see what role everyone was. An easy way to work around this would be to put it in a big text buffer and display it somewhere in the lobby (probably on the right side, but that may cause issues if a line is particularly long, so it may be easier to put it on the left side). This should definitely list player names and roles. If possible it should include things like who the Executioner's target was.

This should probably reflect reality as the game _started_, so someone becoming the Phantom or changing roles because of Shifter wouldn't show up.

**Comment by VirusTLNR** [comment]
This is already done in tor..

Probably adding it to the scene like is done with the version information for the lobby, juat add it on another area, may just require holding back the info from the previous game.

I'll try have a look at this later.

**Comment by VirusTLNR** [comment]
I've got this sort of working, using layout code from tor to set the layout, and pulling data from within tou, but coming across a problem.

I'm pulling playercontrol from the start of the game, and when getting the role of that data, its coming up as none. (Ie, no role)

I assume I'm copying the player control (impostors and cremate from the role assignment area) too early but I wondered if there is something else wrong, I'm using utils.getrole(playercontrol) (not exact coding btw as I'm on my phone not at home).

I just assumed if I copy the player controls and used them with get role  it would get the role of that player control from within tou. But guess I was wrong.

Best current result is a list of names shuffled (so order doesn't reveal the player id number), the rest is wip.

**Comment by VirusTLNR** [comment]
so an update on this now ive actually had the time to work on some things.

I have it working in relation to code for 2.6.2, ill update it to 2.6.3/2.7.0 when im fully done although i assume that wont be much of a change., but there are some extra things i have been trying to add in which are currently not working, ill look into continuing this tomorrow..

currently it lists name, role, and tasks completed/total tasks, the methods ive wrote can be used to also add this information into meetings for dead people if so desired (for example.. players task counts).

you will notice in the screenshot below some blank rows, this is where i plan to add in role changes.. so at the end of the game, where players have changed roles mid-game, the game will make this clear to everyone so you can see all the roles (probably abbreviated, or similar to save on space)

i also plan to add in colours for player names, and roles, only just got the role+tasks side of things working properly in the last hour, will hopefully have time tomorrow evening to do the rest, should only take an hour.

![image](https://user-images.githubusercontent.com/80432742/145312041-e7985a07-e209-4857-b361-711a72f7993e.png)


edit:- oh forgot one more thing i need to do, check what roles have their own "tasks" and set the above to ignore those completely , and hid the task count for roles without tasks too.

edit2:- forgot.. should add modifiers too seeing as only giant is easily known ;)

**Comment by VirusTLNR** [comment]
initial draft pr here.
https://github.com/Anusien/Town-Of-Us/pull/155

will work on the bugs tomorrow, btw i assumed lobby meant the endgame screen, as there is a chance the lobby may close before people get to the new lobby room.. this should be transferable to the lobby as well if required.
