### ISSUE TITLE
Roles given while dead should have their own category(s?) as they dont seem to be tied to neutral roles limits

### ISSUE THREAD

**Issue by VirusTLNR** [Anusien/Town-Of-Us#95]
i was playing with max Neutral roles = 1 (testing phantom update im working on) and i did another stupid thing.. 

i was trying to get phantom every game on one specific person.. and i stupidly chose the other 2 roles turned on as both neutral, so that makes 3 neutral roles with 1 impostor. and only 1 neutral allowed.. meaning no phantom sometimes?

but no.. the roles were.. 1 ximpostor.. 2 x crew and 1 x executioner... so i was like "oh no phantom, kill quick, start again"... killed the non-target crew.. did meeting.. got a phantom,

if phantom does not count in the "neutral roles" limit, it should be made clear (if not already).. but perhaps instead.. there should be a list of "dead crew roles" and "dead neutral roles" and "dead impostor roles" where people can change to these roles after death...? they become SUB ROLES rather than full roles... 

so for example.. a neutral or crew dies... they become PHANTOM.. but their role would be listed as for example "Glitch-Phantom".. there would be no extra abilities, but the game would recognise their old role and their new.

then.. for example, there would be a CREW ghost role which helps aid crew and wins with crew.

and also there could be an impostor dead role that aids impostors while dead.. and only happens to the first impostor who dies/is ejected.

in the case of the phantom, it would stay the same.
in the case of the crew one they would be working with crew (perhaps visible to crew?)
in the case of the impostor one, they would be working with the impostors (Perhaps visible to impostors?)

perhaps even the 3 dead roles can "click" on each other to remove each other from the game?

many ideas... but at the least, phantom should be noted as not being included in neutral role limits.

**Comment by Anusien** [comment]
I am not sure how excited I am to have more ghost roles.

**Comment by VirusTLNR** [comment]
closing this as https://github.com/Anusien/Town-Of-Us/issues/164 has a more relevent title and is talking effectivly about the same issue.
